simulation_node:
  ros__parameters:
    rock_structure_box:
      dimensions: [1.0, 2.0, 3.0]
      mass: 5000.0
      restitution: 0.1
      lateralFriction: 0.6
      spinningFriction: 0.3
      rollingFriction: 0.3
      contactDamping: 10000.0
      contactStiffness: 1000000.0
      localInertiaDiagonal: [5416.66, 4166.67, 2083.33]
      rock_position: [0.0, 0.0, 4.5]