/**:
  ros__parameters:
    dynamics:
      world_box:
        restitution: 0.0
        lateralFriction: 1.5
        spinningFriction: 1.5
        rollingFriction: 1.5
        contactDamping: 1.0
        contactStiffness: 100000.0
      pedestal:
        restitution: 0.0
        lateralFriction: 1.5
        spinningFriction: 1.5
        rollingFriction: 1.5
        contactDamping: 1.0
        contactStiffness: 100000.0
      
      