/**:
  ros__parameters:
    rock_structure_mesh:
      meshScale: [1.0, 1.0, 1.0]
      mass: 353.8022
      restitution: 0.3
      lateralFriction: 0.5
      spinningFriction: 0.3
      contactDamping: 20000.0
      contactStiffness: 2000000.0
      rock_position: [0.0, 0.0, 2.8]
      mesh: /home/zhiang/ros2_ws/src/virtual_shake_robot_pybullet/models/SP1_PBRmodel/sp1.urdf
