simulation_node:
  ros__parameters:
    rock_structure_mesh:
      mesh: "/home/akshay/ros2_ws/virtual_shake_robot_pybullet/models/SP2_PBRmodel/sp2.urdf"
      meshScale: [1.0, 1.0, 1.0]
      mass: 353.802
      restitution: 0.3
      lateralFriction: 0.5
      spinningFriction: 0.3
      rollingFriction: 0.3
      contactDamping: 1.0
      contactStiffness: 100000.0
